name: llama_dart
description: A Dart package for interfacing with llama.cpp models using FFI
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ffi: ^2.1.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
  ffigen: ^11.0.0